// ============================================================
//  GOODS GALLARRY – PRODUCTS DATA (GBP £, UK)
// ============================================================
const WHATSAPP_NUMBER = "447508234409";
const STORE_NAME = "Goods Gallarry";
const STORE_ADDRESS = "17 Ipswich Street, Rochdale, United Kingdom, OL11 1JS";
const STORE_PHONE = "+447508234409";
const STORE_EMAIL = "support@goodsgallarry.co.uk";

const PRODUCTS = [
  // ── AUDIO (Headphones + Earbuds + Earphones combined) ──
  {
    id: 1,
    name: "Pro Noise Cancelling Headphones",
    brand: "Goods Gallarry",
    category: "audio",
    price: 69.99, oldPrice: 89.99,
    colors: ["#111827","#b45309","#1d4ed8"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80"],
    badge: "Save £20", rating: 4.8, reviews: 341,
    description: "Industry-leading active noise cancellation with 30-hour battery life.",
    features: ["Active Noise Cancel","30hr Battery","Hi-Res Audio","Foldable Design","Multi-device"],
  },
  {
    id: 2,
    name: "Open Ear Wireless Earbuds",
    brand: "Goods Gallarry",
    category: "audio",
    price: 34.99, oldPrice: 44.99,
    colors: ["#111827","#f3f4f6"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80"],
    badge: "New", rating: 4.7, reviews: 212,
    description: "Open-ear design with bone conduction technology.",
    features: ["Open Ear Design","8hr Battery","IPX5 Waterproof","Bluetooth 5.3","Touch Controls"],
  },
  {
    id: 3,
    name: "Premium In-Ear Earphones",
    brand: "Goods Gallarry",
    category: "audio",
    price: 14.99, oldPrice: 19.99,
    colors: ["#111827","#f3f4f6","#ef4444"],
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80"],
    badge: "Save £5", rating: 4.3, reviews: 278,
    description: "Wired in-ear earphones with 10mm dynamic drivers and inline microphone.",
    features: ["10mm Drivers","3.5mm Jack","Inline Mic","Tangle-Free","3 Ear Tip Sizes"],
  },

  // ── MOBILE & TABLETS ──
  {
    id: 4,
    name: "ProMax 5G Smartphone",
    brand: "Goods Gallarry",
    category: "mobile-tablet",
    price: 549.99, oldPrice: 649.99,
    colors: ["#6b21a8","#1d4ed8","#111827","#d1d5db"],
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80"],
    badge: "Save £100", rating: 4.8, reviews: 520,
    description: "Flagship 5G smartphone with 200MP camera, Snapdragon 8 Gen 3.",
    features: ["200MP Camera","Snapdragon 8 Gen 3","5G Ready","5000mAh Battery","Fast Charge 65W"],
  },
  {
    id: 5,
    name: "UltraSlim A55 Android Phone",
    brand: "Goods Gallarry",
    category: "mobile-tablet",
    price: 349.99, oldPrice: 429.99,
    colors: ["#1e40af","#111827","#d4d4d4","#7c3aed"],
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80"],
    badge: "Save £80", rating: 4.5, reviews: 310,
    description: "Sleek mid-range smartphone with 6.5-inch Super AMOLED, 108MP camera.",
    features: ["108MP Camera","6.5\" Super AMOLED","4500mAh","64MP Selfie","5G Ready"],
  },
  {
    id: 6,
    name: "Budget Smart 4G Phone",
    brand: "Goods Gallarry",
    category: "mobile-tablet",
    price: 129.99, oldPrice: 169.99,
    colors: ["#065f46","#1e3a5f","#111827","#fbbf24"],
    image: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&q=80"],
    badge: "Save £40", rating: 4.1, reviews: 198,
    description: "Affordable 4G smartphone with large battery and dual camera.",
    features: ["48MP Dual Camera","6000mAh Battery","6.3\" HD+","4GB RAM","Face Unlock"],
  },
  {
    id: 7,
    name: "Galaxy Tab Pro 11-inch Tablet",
    brand: "Goods Gallarry",
    category: "mobile-tablet",
    price: 299.99, oldPrice: 369.99,
    colors: ["#111827","#c0c0c0","#1d4ed8"],
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80"],
    badge: "Save £70", rating: 4.6, reviews: 156,
    description: "11-inch AMOLED display tablet with S-Pen support and DeX mode.",
    features: ["11\" AMOLED","S-Pen Included","12GB RAM","256GB Storage","DeX Mode"],
  },

  // ── LAPTOPS ──
  {
    id: 8,
    name: "UltraBook Pro 14-inch Laptop",
    brand: "Goods Gallarry",
    category: "laptop",
    price: 649.99, oldPrice: 799.99,
    colors: ["#c0c0c0","#b8860b","#111827"],
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80"],
    badge: "Save £150", rating: 4.7, reviews: 189,
    description: "Slim and powerful 14-inch laptop with i7 processor, 16GB RAM, 512GB SSD.",
    features: ["Intel i7 12th Gen","16GB DDR5 RAM","512GB NVMe SSD","14\" FHD IPS","Backlit KB"],
  },
  {
    id: 9,
    name: "Laptop Hardshell Protective Case",
    brand: "Goods Gallarry",
    category: "laptop",
    price: 19.99, oldPrice: 27.99,
    colors: ["#111827","#ef4444","#3b82f6","#10b981"],
    image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&q=80"],
    badge: "Save £8", rating: 4.2, reviews: 44,
    description: "Hard-shell protective case for laptops 13-16 inch.",
    features: ["Universal 13\"-16\"","Shock Proof","Water Resistant","Multiple Colors","Easy Access"],
  },

  // ── ACCESSORIES (Keyboard + Pen Drive) ──
  {
    id: 10,
    name: "KeyPop Combo Keyboard & Mouse",
    brand: "Goods Gallarry",
    category: "accessories",
    price: 24.99, oldPrice: 32.99,
    colors: ["#6b7280","#f59e0b","#10b981","#3b82f6"],
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=600&q=80"],
    badge: "Save £8", rating: 4.3, reviews: 95,
    description: "Retro-style wireless keyboard and mouse combo with RGB backlit keys.",
    features: ["Wireless 2.4GHz","Retro Keycaps","RGB Backlit","1600 DPI Mouse","Battery 12 months"],
  },
  {
    id: 11,
    name: "128GB USB 3.0 Flash Drive",
    brand: "Goods Gallarry",
    category: "accessories",
    price: 9.99, oldPrice: 14.99,
    colors: ["#111827","#3b82f6","#ef4444"],
    image: "https://images.unsplash.com/photo-1618424181497-157f25b6ddd5?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1618424181497-157f25b6ddd5?w=600&q=80"],
    badge: "Save £5", rating: 4.2, reviews: 193,
    description: "High-speed 128GB USB 3.0 flash drive. Read speeds up to 200MB/s.",
    features: ["128GB Storage","USB 3.0","200MB/s Read","Metal Body","Retractable Cap"],
  },
  {
    id: 12,
    name: "Compact Pocket Size Power Bank",
    brand: "Goods Gallarry",
    category: "accessories",
    price: 12.99, oldPrice: 16.99,
    colors: ["#c084fc","#f9a8d4","#a3e635","#fbbf24"],
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&q=80",
    images: ["https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80"],
    badge: "Save £4", rating: 4.5, reviews: 128,
    description: "Ultra-compact 10,000mAh power bank with fast charging support.",
    features: ["10,000 mAh","Fast Charging 18W","Type-C & USB-A","LED Indicator","180g"],
  },

  // ── VITAMINS & SUPPLEMENTS ──
  {
    id: 13,
    name: "BetterVits Magnesium Complex",
    brand: "BetterVits",
    category: "vitamins",
    price: 14.99, oldPrice: 19.99,
    colors: [],
    image: "vit1.jpg",
    images: ["vit1.jpg","vit2.jpg"],
    badge: "Save £5", rating: 4.6, reviews: 312,
    description: "High-strength Magnesium Complex with Glycinate & Citrate for muscle, nerve and sleep support.",
    features: ["Magnesium Glycinate","Magnesium Citrate","180 Capsules","Non-GMO","Made in UK"],
  },
  {
    id: 14,
    name: "BetterVits Glucosamine Complex",
    brand: "BetterVits",
    category: "vitamins",
    price: 16.99, oldPrice: 22.99,
    colors: [],
    image: "vit3.jpg",
    images: ["vit3.jpg"],
    badge: "Save £6", rating: 4.5, reviews: 198,
    description: "Glucosamine with Chondroitin & Turmeric for joint health and inflammation support.",
    features: ["Glucosamine","Chondroitin","Turmeric","120 Capsules","UK Manufactured"],
  },
  {
    id: 15,
    name: "BetterVits Collagen Supplement",
    brand: "BetterVits",
    category: "vitamins",
    price: 18.99, oldPrice: 24.99,
    colors: [],
    image: "vit4.jpg",
    images: ["vit4.jpg"],
    badge: "Save £6", rating: 4.4, reviews: 156,
    description: "Hydrolyzed Collagen with Hyaluronic Acid for skin, hair and nail health.",
    features: ["Hydrolyzed Collagen","Hyaluronic Acid","Vitamin C","90 Capsules","Skin Health"],
  },
  {
    id: 16,
    name: "Hey Nutrition Probiotic",
    brand: "Hey Nutrition",
    category: "vitamins",
    price: 12.99, oldPrice: 17.99,
    colors: [],
    image: "vit5.jpg",
    images: ["vit5.jpg"],
    badge: "Save £5", rating: 4.3, reviews: 89,
    description: "High-strength probiotic supplement for gut health and immune support.",
    features: ["50 Billion CFU","10 Strains","Gut Health","Immune Support","60 Capsules"],
  },

  // ── SPORTS SUPPLEMENTS ──
  {
    id: 17,
    name: "ON Gold Standard Whey Protein",
    brand: "Optimum Nutrition",
    category: "sports",
    price: 34.99, oldPrice: 44.99,
    colors: [],
    image: "sport1.jpg",
    images: ["sport1.jpg","sport5.jpg"],
    badge: "Save £10", rating: 4.9, reviews: 8420,
    description: "24g protein per serving, Double Rich Chocolate. The world's best-selling whey protein.",
    features: ["24g Protein","Low Sugar","BCAA","Glutamine","30 Servings"],
  },
  {
    id: 18,
    name: "Applied Nutrition Diet Whey",
    brand: "Applied Nutrition",
    category: "sports",
    price: 24.99, oldPrice: 32.99,
    colors: [],
    image: "sport2.jpg",
    images: ["sport2.jpg"],
    badge: "Save £8", rating: 4.6, reviews: 2150,
    description: "High protein, low carb diet whey for weight management and lean muscle.",
    features: ["High Protein","Low Carb","Low Sugar","Weight Management","Multiple Flavours"],
  },
  {
    id: 19,
    name: "SCI-MX Ultra Muscle Protein",
    brand: "SCI-MX",
    category: "sports",
    price: 29.99, oldPrice: 39.99,
    colors: [],
    image: "sport3.jpg",
    images: ["sport3.jpg"],
    badge: "Save £10", rating: 4.5, reviews: 1230,
    description: "Ultra Muscle protein powder for serious muscle development.",
    features: ["High Protein","Muscle Growth","Post-Workout","Multiple Flavours","2kg"],
  },
  {
    id: 20,
    name: "HIGH5 ZERO Electrolyte Tablets",
    brand: "HIGH5",
    category: "sports",
    price: 7.99, oldPrice: 10.99,
    colors: [],
    image: "sport4.jpg",
    images: ["sport4.jpg"],
    badge: "Save £3", rating: 4.7, reviews: 3400,
    description: "Zero calorie electrolyte tablets with Vitamin C for hydration during exercise.",
    features: ["Zero Calories","Vitamin C","Electrolytes","20 Tablets","Multiple Flavours"],
  },

  // ── PERFUME ──
  {
    id: 21,
    name: "Chanel Coco EDP 100ml",
    brand: "Chanel",
    category: "perfume",
    price: 89.99, oldPrice: 109.99,
    colors: [],
    image: "perf1.jpg",
    images: ["perf1.jpg","perf2.jpg"],
    badge: "Save £20", rating: 4.9, reviews: 5600,
    description: "Chanel Coco 100ml Eau de Parfum for Women. Classic oriental floral fragrance.",
    features: ["100ml EDP","Women's Fragrance","Long Lasting","Iconic Scent","Gift Box"],
  },
  {
    id: 22,
    name: "Mugler Alien Eau de Parfum",
    brand: "Mugler",
    category: "perfume",
    price: 69.99, oldPrice: 89.99,
    colors: [],
    image: "perf3.jpg",
    images: ["perf3.jpg","perf4.jpg"],
    badge: "Save £20", rating: 4.8, reviews: 3200,
    description: "Refillable Alien EDP with Jasmine Sambac and White Amber. Iconic woody floral scent.",
    features: ["Refillable Bottle","Jasmine Sambac","White Amber","Long Lasting","Women's"],
  },
  {
    id: 23,
    name: "Mugler Alien Pulp EDP",
    brand: "Mugler",
    category: "perfume",
    price: 64.99, oldPrice: 79.99,
    colors: [],
    image: "perf5.jpg",
    images: ["perf5.jpg"],
    badge: "Save £15", rating: 4.7, reviews: 1890,
    description: "Fruity floral scent with Raspberry Accord, Creamy Jasmine and Musk.",
    features: ["Raspberry Accord","Creamy Jasmine","Musk","Refillable","Women's Fragrance"],
  },

  // ── PET SUPPLIES ──
  {
    id: 24,
    name: "FRONTLINE Plus Cats & Ferrets",
    brand: "FRONTLINE",
    category: "pet",
    price: 19.99, oldPrice: 26.99,
    colors: [],
    image: "pet1.jpg",
    images: ["pet1.jpg"],
    badge: "Save £7", rating: 4.8, reviews: 4200,
    description: "Flea & Tick treatment for cats and ferrets. 6 pipettes. Kills fleas, ticks and lice.",
    features: ["6 Pipettes","Cats & Ferrets","Kills Fleas & Ticks","Waterproof","Vet Recommended"],
  },
  {
    id: 25,
    name: "FRONTLINE Plus Small Dogs (2-10kg)",
    brand: "FRONTLINE",
    category: "pet",
    price: 21.99, oldPrice: 28.99,
    colors: [],
    image: "pet2.jpg",
    images: ["pet2.jpg"],
    badge: "Save £7", rating: 4.9, reviews: 6800,
    description: "Flea & Tick treatment for small dogs 2-10kg. 6 pipettes pack.",
    features: ["6 Pipettes","Dogs 2-10kg","Kills Fleas & Ticks","Waterproof","Vet Recommended"],
  },
  {
    id: 26,
    name: "FRONTLINE Plus Medium Dogs (10-20kg)",
    brand: "FRONTLINE",
    category: "pet",
    price: 23.99, oldPrice: 30.99,
    colors: [],
    image: "pet3.jpg",
    images: ["pet3.jpg"],
    badge: "Save £7", rating: 4.9, reviews: 5400,
    description: "Flea & Tick treatment for medium dogs 10-20kg. 6 pipettes pack.",
    features: ["6 Pipettes","Dogs 10-20kg","Kills Fleas & Ticks","Waterproof","Vet Recommended"],
  },
  {
    id: 27,
    name: "FRONTLINE Plus Large Dogs (20-40kg)",
    brand: "FRONTLINE",
    category: "pet",
    price: 25.99, oldPrice: 33.99,
    colors: [],
    image: "pet4.jpg",
    images: ["pet4.jpg"],
    badge: "Save £8", rating: 4.9, reviews: 4900,
    description: "Flea & Tick treatment for large dogs 20-40kg. 6 pipettes pack.",
    features: ["6 Pipettes","Dogs 20-40kg","Kills Fleas & Ticks","Waterproof","Vet Recommended"],
  },
  {
    id: 28,
    name: "NutriPaw All-Itch Immunity Treats",
    brand: "NutriPaw",
    category: "pet",
    price: 17.99, oldPrice: 23.99,
    colors: [],
    image: "pet5.jpg",
    images: ["pet5.jpg"],
    badge: "Save £6", rating: 4.7, reviews: 2300,
    description: "Soothes itchy paws, eyes, ears and skin. Stops itching, licking and scratching.",
    features: ["Stops Itching","All Dog Sizes","Seasonal Itching","Natural Ingredients","60 Treats"],
  },
  {
    id: 29,
    name: "NutriPaw Probiotic Digestive Treats",
    brand: "NutriPaw",
    category: "pet",
    price: 16.99, oldPrice: 22.99,
    colors: [],
    image: "pet6.jpg",
    images: ["pet6.jpg"],
    badge: "Save £6", rating: 4.6, reviews: 1870,
    description: "Pre, Pro & Postbiotic treats for gut health, sensitive tummies and anal glands.",
    features: ["Probiotic","Prebiotic","Gut Health","Sensitive Tums","60 Treats"],
  },

  // ── HOME & KITCHEN ──
  {
    id: 30,
    name: "Handheld Portable Blender",
    brand: "Goods Gallarry",
    category: "home",
    price: 18.99, oldPrice: 24.99,
    colors: [],
    image: "home1.jpg",
    images: ["home1.jpg"],
    badge: "Save £6", rating: 4.5, reviews: 890,
    description: "Portable rechargeable handheld blender for smoothies and protein shakes on the go.",
    features: ["Rechargeable USB","Portable","Easy Clean","6 Blades","BPA Free"],
  },
  {
    id: 31,
    name: "ANSIO Electric Dehumidifier",
    brand: "ANSIO",
    category: "home",
    price: 39.99, oldPrice: 52.99,
    colors: [],
    image: "home5.png",
    images: ["home5.png"],
    badge: "Save £13", rating: 4.4, reviews: 1230,
    description: "Compact electric dehumidifier for home use. Removes moisture and prevents damp.",
    features: ["750ml Tank","Auto Off","Silent Operation","Energy Efficient","UK Plug"],
  },
  {
    id: 32,
    name: "Budding Joy 90L Storage Bags (6 Pack)",
    brand: "Budding Joy",
    category: "home",
    price: 22.99, oldPrice: 29.99,
    colors: [],
    image: "home2.jpg",
    images: ["home2.jpg"],
    badge: "Save £7", rating: 4.6, reviews: 2100,
    description: "Large clothes storage bags with zips and handles for clothes, bedding and blankets.",
    features: ["6 Pack","90L Each","Durable Handles","Zip Closure","Grey"],
  },
  {
    id: 33,
    name: "BYKITCHEN Air Fryer Liners (50 PCS)",
    brand: "BYKITCHEN",
    category: "home",
    price: 8.99, oldPrice: 12.99,
    colors: [],
    image: "home3.jpg",
    images: ["home3.jpg"],
    badge: "Save £4", rating: 4.7, reviews: 3400,
    description: "Disposable parchment paper liners for air fryers. Compatible with COSORI, Ninja, Tefal.",
    features: ["50 PCS","Greaseproof","Unbleached","Multi Brand Fit","Easy Clean"],
  },
  {
    id: 34,
    name: "Lifewit 95L Storage Bags (3 Pack)",
    brand: "Lifewit",
    category: "home",
    price: 24.99, oldPrice: 32.99,
    colors: [],
    image: "home4.jpg",
    images: ["home4.jpg"],
    badge: "Save £8", rating: 4.5, reviews: 1760,
    description: "Extra large storage boxes with clear window and reinforced handles.",
    features: ["3 Pack","95L Each","Clear Window","Reinforced Handle","Thick Fabric"],
  },

  // ── GROCERY ──
  {
    id: 35,
    name: "Andrex Family Soft Toilet Paper 24 Rolls",
    brand: "Andrex",
    category: "grocery",
    price: 8.99, oldPrice: 11.99,
    colors: [],
    image: "groc1.jpg",
    images: ["groc1.jpg"],
    badge: "Save £3", rating: 4.8, reviews: 12400,
    description: "Andrex Family Soft toilet paper 24 rolls. Soft, strong and gentle.",
    features: ["24 Rolls","Family Soft","Strong","Gentle","Sustainably Sourced"],
  },
  {
    id: 36,
    name: "Velvet Classic Quilted Toilet Tissue 24 Rolls",
    brand: "Velvet",
    category: "grocery",
    price: 7.99, oldPrice: 10.99,
    colors: [],
    image: "groc2.jpg",
    images: ["groc2.jpg"],
    badge: "Save £3", rating: 4.7, reviews: 8900,
    description: "Triple quilted luxury toilet tissue. Soft and thick for extra comfort.",
    features: ["24 Rolls","Triple Quilted","Ultra Soft","Thick","Jumbo Roll"],
  },
  {
    id: 37,
    name: "Amazon Kitchen Towel Certified",
    brand: "Amazon",
    category: "grocery",
    price: 5.99, oldPrice: 7.99,
    colors: [],
    image: "groc3.jpg",
    images: ["groc3.jpg"],
    badge: "Save £2", rating: 4.6, reviews: 6700,
    description: "Super absorbent kitchen towel, certified and eco-friendly.",
    features: ["Super Absorbent","Eco-Certified","Strong","Large Sheets","2 Ply"],
  },
  {
    id: 38,
    name: "Regina Blitz Household Towels",
    brand: "Regina",
    category: "grocery",
    price: 6.49, oldPrice: 8.99,
    colors: [],
    image: "groc4.jpg",
    images: ["groc4.jpg"],
    badge: "Save £2.50", rating: 4.5, reviews: 4300,
    description: "Regina Blitz super absorbent household paper towels. Great for spills.",
    features: ["Super Absorbent","Strong","White","Large Sheets","Multi Pack"],
  },
  {
    id: 39,
    name: "Persil Bio Washing Capsules 48 Washes",
    brand: "Persil",
    category: "grocery",
    price: 9.99, oldPrice: 13.99,
    colors: [],
    image: "groc5.jpg",
    images: ["groc5.jpg"],
    badge: "Save £4", rating: 4.7, reviews: 7800,
    description: "Bio 3-in-1 capsules for tough stain removal in quick and cold washes.",
    features: ["48 Washes","3-in-1","Stain Removal","Cold Wash","Quick Wash"],
  },
  {
    id: 40,
    name: "Finish Dishwasher Salt 2kg",
    brand: "Finish",
    category: "grocery",
    price: 4.49, oldPrice: 6.49,
    colors: [],
    image: "groc6.jpg",
    images: ["groc6.jpg"],
    badge: "Save £2", rating: 4.8, reviews: 9200,
    description: "Prevents limescale and white residue. For cleaner and shinier dishes.",
    features: ["2kg","Anti-Limescale","Prevents Residue","Hard Water","For All Dishwashers"],
  },

  // ── STATIONERY & OFFICE ──
  {
    id: 41,
    name: "Sharpie Permanent Markers Black (2 Pack)",
    brand: "Sharpie",
    category: "stationery",
    price: 3.99, oldPrice: 5.99,
    colors: [],
    image: "stat1.jpg",
    images: ["stat1.jpg"],
    badge: "Save £2", rating: 4.9, reviews: 15600,
    description: "Fine point permanent markers in black ink. Perfect for bold details.",
    features: ["2 Pack","Fine Point","Permanent Ink","Black","Water Resistant"],
  },
  {
    id: 42,
    name: "Zebra Z-Grip Black Ballpoint Pens 8 Pack",
    brand: "Zebra",
    category: "stationery",
    price: 5.99, oldPrice: 7.99,
    colors: [],
    image: "stat2.jpg",
    images: ["stat2.jpg"],
    badge: "Save £2", rating: 4.8, reviews: 8900,
    description: "Retractable black ink ballpoint pens with pocket clip. Reliable everyday biros.",
    features: ["8 Pack","Retractable","Pocket Clip","Smooth Ink","Everyday Use"],
  },
  {
    id: 43,
    name: "A4 Printer Paper 500 Sheets",
    brand: "Stick N Well",
    category: "stationery",
    price: 6.99, oldPrice: 9.99,
    colors: [],
    image: "stat3.jpg",
    images: ["stat3.jpg"],
    badge: "Save £3", rating: 4.7, reviews: 5400,
    description: "White A4 printer paper 500 sheets. Compatible with inkjet, laser printers and copiers.",
    features: ["500 Sheets","A4 Size","80gsm","Inkjet & Laser","Multipurpose"],
  },
  {
    id: 44,
    name: "Thermal Shipping Label Rolls",
    brand: "Double Dragon",
    category: "stationery",
    price: 12.99, oldPrice: 17.99,
    colors: [],
    image: "stat4.jpg",
    images: ["stat4.jpg"],
    badge: "Save £5", rating: 4.6, reviews: 3200,
    description: "Direct thermal shipping label rolls. Self-adhesive, compatible with most thermal printers.",
    features: ["Self-Adhesive","Thermal Print","Compatible","Strong Adhesive","Business Use"],
  },
  {
    id: 45,
    name: "Cardboard Storage Moving Boxes (10 Pack)",
    brand: "Rainberg",
    category: "stationery",
    price: 19.99, oldPrice: 27.99,
    colors: [],
    image: "stat5.jpg",
    images: ["stat5.jpg"],
    badge: "Save £8", rating: 4.5, reviews: 2100,
    description: "10 strong large cardboard storage boxes with fragile tape and carry handles.",
    features: ["10 Pack","47L Each","Carry Handles","Fragile Tape","Recyclable"],
  },

  // ── GARDEN ──
  {
    id: 46,
    name: "Roundup Fast Action Weedkiller 5L",
    brand: "Roundup",
    category: "garden",
    price: 14.99, oldPrice: 19.99,
    colors: [],
    image: "gard1.jpg",
    images: ["gard1.jpg"],
    badge: "Save £5", rating: 4.6, reviews: 3400,
    description: "Pump N Go 5L ready-to-use weedkiller. Fast action glyphosate formula.",
    features: ["5L Ready to Use","Pump N Go","Fast Action","Glyphosate","Kills Roots"],
  },
  {
    id: 47,
    name: "Spear & Jackson 5L Pressure Sprayer",
    brand: "Spear & Jackson",
    category: "garden",
    price: 12.99, oldPrice: 17.99,
    colors: [],
    image: "gard2.jpg",
    images: ["gard2.jpg"],
    badge: "Save £5", rating: 4.5, reviews: 2100,
    description: "5 litre pump action pressure sprayer for garden use.",
    features: ["5L Capacity","Pump Action","Adjustable Nozzle","Garden Use","Durable"],
  },
  {
    id: 48,
    name: "Miracle-Gro Liquid Plant Food 800ml",
    brand: "Miracle-Gro",
    category: "garden",
    price: 7.99, oldPrice: 10.99,
    colors: [],
    image: "gard3.jpg",
    images: ["gard3.jpg"],
    badge: "Save £3", rating: 4.7, reviews: 4500,
    description: "All purpose concentrated liquid plant food 800ml. For all plants indoors and outdoors.",
    features: ["800ml","All Purpose","Concentrated","Indoor & Outdoor","NPK Formula"],
  },
  {
    id: 49,
    name: "NOPE! Ant Killer Bait Station (6 Pack)",
    brand: "NOPE!",
    category: "garden",
    price: 8.99, oldPrice: 12.99,
    colors: [],
    image: "gard4.jpg",
    images: ["gard4.jpg"],
    badge: "Save £4", rating: 4.4, reviews: 1890,
    description: "Ant killer bait stations for indoor and outdoor use. Eradicates ants and colonies.",
    features: ["6 Bait Stations","Indoor & Outdoor","Kills Colony","Long Lasting","Child Safe"],
  },
  {
    id: 50,
    name: "ROSHIELD Rat & Mouse Poison Blocks 300g",
    brand: "ROSHIELD",
    category: "garden",
    price: 9.99, oldPrice: 13.99,
    colors: [],
    image: "gard5.jpg",
    images: ["gard5.jpg"],
    badge: "Save £4", rating: 4.3, reviews: 1240,
    description: "Rat and mouse poison blocks 300g. Single feed formula for fast results.",
    features: ["300g","Single Feed","Rats & Mice","Fast Results","Outdoor Use"],
  },
];

function formatPrice(p) {
  return "£" + p.toFixed(2);
}

function starHTML(rating) {
  let s = "";
  for (let i = 1; i <= 5; i++) {
    if (i <= Math.floor(rating)) s += "★";
    else if (i - rating < 1) s += "½";
    else s += "☆";
  }
  return `<span class="stars">${s}</span> <span class="rev-count">(${rating})</span>`;
}

function buildCard(p) {
  const isNew = p.badge === "New";
  const badgeClass = isNew ? "badge badge-new" : "badge";
  return `
    <div class="product-card" data-id="${p.id}">
      ${p.badge ? `<span class="${badgeClass}">${p.badge}</span>` : ""}
      <a href="detail.html?id=${p.id}">
        <div class="card-img-wrap">
          <img src="${p.image}" alt="${p.name}" loading="lazy"/>
          <div class="quick-look">Quick Look</div>
        </div>
      </a>
      <div class="card-body">
        <p class="card-brand">${p.brand}</p>
        <a href="detail.html?id=${p.id}"><h3 class="card-name">${p.name}</h3></a>
        <div class="card-prices">
          <span class="price-new">${formatPrice(p.price)}</span>
          <span class="price-old">${formatPrice(p.oldPrice)}</span>
        </div>
        ${p.colors && p.colors.length ? `<div class="color-dots">${p.colors.map(c=>`<span class="dot" style="background:${c}"></span>`).join("")}</div>` : ""}
        <button class="btn-add-cart" onclick="addToCart(${p.id})">🛒 Add to Cart</button>
      </div>
    </div>
  `;
}

function orderOnWhatsApp(cartItems, total) {
  let msg = `Hello ${STORE_NAME}! 👋\n\nI would like to place an order:\n\n`;
  cartItems.forEach(item => {
    msg += `• ${item.name} x${item.qty} = ${formatPrice(item.price * item.qty)}\n`;
  });
  msg += `\n*Total: ${formatPrice(total)}*\n\nDelivery to: \n\nPlease confirm my order. Thank you!`;
  window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`, "_blank");
}
